import type { Company } from './types';

export const companiesSeed: Company[] = [
  {
    id: 'cmp-northline',
    name: 'Northline HVAC',
    ownerName: 'Alex Morgan',
    ownerEmail: 'alex@northline.example',
    domain: 'northline.servicescope.app',
    market: 'New York, NY',
    plan: 'Growth',
    status: 'active',
    billingStatus: 'paid',
    seats: 24,
    technicians: 18,
    openJobs: 42,
    revenue: 128400,
    health: 91,
    lastSync: '4 min ago',
    onboarding: {
      workspace: 'done',
      users: 'done',
      data: 'done',
      billing: 'done',
    },
    alerts: ['High job volume this week'],
    usage: {
      jobsThisMonth: 386,
      invoicesThisMonth: 219,
      storageGb: 18.4,
    },
  },
  {
    id: 'cmp-apex',
    name: 'Apex Service Co',
    ownerName: 'Maria Chen',
    ownerEmail: 'maria@apex.example',
    domain: 'apex.servicescope.app',
    market: 'Jersey City, NJ',
    plan: 'Launch',
    status: 'trial',
    billingStatus: 'trialing',
    seats: 10,
    technicians: 7,
    openJobs: 15,
    revenue: 27300,
    health: 76,
    lastSync: '18 min ago',
    onboarding: {
      workspace: 'done',
      users: 'done',
      data: 'current',
      billing: 'todo',
    },
    alerts: ['Import waiting for customer CSV'],
    usage: {
      jobsThisMonth: 92,
      invoicesThisMonth: 41,
      storageGb: 4.9,
    },
  },
  {
    id: 'cmp-summit',
    name: 'Summit Mechanical',
    ownerName: 'Brian Ellis',
    ownerEmail: 'brian@summit.example',
    domain: 'summit.servicescope.app',
    market: 'Stamford, CT',
    plan: 'Scale',
    status: 'setup',
    billingStatus: 'not_started',
    seats: 35,
    technicians: 24,
    openJobs: 8,
    revenue: 0,
    health: 63,
    lastSync: 'Needs setup',
    onboarding: {
      workspace: 'done',
      users: 'current',
      data: 'todo',
      billing: 'blocked',
    },
    alerts: ['Billing contact missing', 'Manager invites pending'],
    usage: {
      jobsThisMonth: 0,
      invoicesThisMonth: 0,
      storageGb: 0.6,
    },
  },
];
